### ISSUE TITLE
adicionar screenshot para as pessoas visualizarem o software antes de baixar, instalar?

### ISSUE THREAD

**Issue by nichdemos** [zekicarvalho/Textim#10]
Oi @zekicarvalho, como vai?

O que acha da ideia de adicionar screenshot para as pessoas visualizarem o software textim-editor antes de baixar, instalar? acha que essa ideia e sugestão faz sentido?

**Comment by zekicarvalho** [comment]
@nichdemos Oi, faz sim, em breve colocarei as screenshots. Tem tanto tempo que eu não acompanho esse projeto que vou precisar atualizar algumas coisas também. Fico feliz com o feedback.
Aliás, se quiser testar na sua máquina seria muito legal.

**Comment by nichdemos** [comment]
Oi @zekicarvalho, como vai? 

> Oi, faz sim, em breve colocarei as screenshots. Tem tanto tempo que eu não acompanho esse projeto que vou precisar atualizar algumas coisas também. Fico feliz com o feedback.

podemos ser amigos aqui no GitHub? (pergunto sobre isso, pois eu trabalho com algumas coisas aqui e acho seu trabalho incrível. como esse projeto aqui).

**Comment by zekicarvalho** [comment]
@nichdemos Bora ressuscitar esse projeto! Te segui aqui no Github. 
Tem mais informações de contato para falar comigo no link do meu portifólio.

**Comment by nichdemos** [comment]
Oi @zekicarvalho, top demais. fiz a conta recentemente no GitHub e é bem legal conhecer galera.
