### ISSUE TITLE
boas novas

### ISSUE THREAD

**Issue by nichdemos** [zekicarvalho/Textim#16]
Oi @zekicarvalho 

Fiz um update com o path: [atualizando caminhos do app textim-editor](https://github.com/zekicarvalho/Textim/pull/14)

o que acha? isso é bom ou ruim?

**Comment by zekicarvalho** [comment]
@nichdemos Vou testar se essa mudança de diretórios influência no NPM, eu acredito que sim.

**Comment by nichdemos** [comment]
Oi @zekicarvalho, tudo bem ^^ aguardo então, e deixo essa issue aberta até você dar resposta. passar bem ;D

**Comment by zekicarvalho** [comment]
Aprovada.
