### ISSUE TITLE
posso divulgar esse projeto para meus amigos desenvolvedores?

### ISSUE THREAD

**Issue by nichdemos** [zekicarvalho/Textim#17]
Oi @zekicarvalho, como tú tá?

eu tenho permissão para divulgar esse projeto para meus amigos desenvolvedores? Existe algum direito de imagem ou marca registrada neste projeto de código aberto que restrinja a divulgação e promoção deste projeto?

**Comment by zekicarvalho** [comment]
@nichdemos Não existe não, pode divulgar a vontade :)

**Comment by nichdemos** [comment]
@zekicarvalho valeu pelo comentar. tamo junto ^^
