### ISSUE TITLE
Criar organização zeki technologies?

### ISSUE THREAD

**Issue by nichdemos** [zekicarvalho/Textim#19]
Oi @zekicarvalho, como vai?

Uma ideia interessante seria criar uma organização do GitHub para inserir os repositórios TextTim e Calen. Acho interessante criar uma organização no GitHub, pois pode haver muitas pessoas interessadas e numa organização do GitHub é possível gerenciar permissões de membros entre outras configurações personalizadas.

O que acha dessa ideia de criar uma organização no GitHub?

**Comment by zekicarvalho** [comment]
Isso é uma ideia que já tive antes, me chame nos meus contatos para te mostrar algumas idéias.

**Comment by ghost** [comment]
Oi @zekicarvalho, que bom que temos ideias parecidas.
